---
on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Debug
        run: pwd && ls -la

      - name: Setup
        run: make setup

      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --all-files
        env:
          SKIP: "no-commit-to-branch"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Debug
        run: pwd && ls -la

      - name: Setup
        run: make setup

      - name: Run pytest
        run: make unit

  pypi:
    runs-on: ubuntu-latest
    needs:
      - test
      - pre-commit
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    needs:
      - test
      - pre-commit
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: make setup

      - name: build docs
        run: make build-docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: pages
          folder: ./site
          token: ${{ secrets.GH_TOKEN }}

  semantic-release:
    uses: rwxd/gh-templates/.github/workflows/common-semantic-release.yml@main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - docs
      - test
      - pre-commit
    secrets:
      token: ${{ secrets.GH_TOKEN }}
